/* automatically generated by rust-bindgen 0.59.2 */

pub type SizeT = ::std::os::raw::c_ulong;
pub type WcharT = ::std::os::raw::c_uint;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[test]
fn bindgen_test_layout_max_align_t() {
    assert_eq!(
        ::std::mem::size_of::<max_align_t>(),
        32usize,
        concat!("Size of: ", stringify!(max_align_t))
    );
    assert_eq!(
        ::std::mem::align_of::<max_align_t>(),
        16usize,
        concat!("Alignment of ", stringify!(max_align_t))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce1 as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(max_align_t),
            "::",
            stringify!(__clang_max_align_nonce1)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce2 as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(max_align_t),
            "::",
            stringify!(__clang_max_align_nonce2)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uws_app_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uws_req_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uws_res_s {
    _unused: [u8; 0],
}
pub type UwsAppT = uws_app_s;
pub type UwsReqT = uws_req_s;
pub type UwsResT = uws_res_s;
extern "C" {
    pub fn uws_create_app() -> *mut UwsAppT;
}
extern "C" {
    pub fn uws_app_get(
        app: *mut UwsAppT,
        pattern: *const ::std::os::raw::c_char,
        handler: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut UwsResT,
                                 arg2: *mut UwsReqT),
        >,
    );
}
extern "C" {
    pub fn uws_app_run(arg1: *mut UwsAppT);
}
extern "C" {
    pub fn uws_app_listen(
        app: *mut UwsAppT,
        port: ::std::os::raw::c_int,
        handler: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
extern "C" {
    pub fn uws_res_end(res: *mut UwsResT, data: *const ::std::os::raw::c_char, length: SizeT, close_connection :bool);
}

extern "C" fn listen_handler(_listen_socket: *mut ::std::os::raw::c_void) {
        println!("Listening");
    
}

extern "C" fn get_handler(res: *mut UwsResT, _: *mut UwsReqT) {
    unsafe {
        let message = ::std::ffi::CString::new("Hello!").expect("");
        uws_res_end(res, message.as_ptr(), 6, false);
    }
}

fn main() {
    unsafe {
        let app = uws_create_app();
        let route = ::std::ffi::CString::new("/*").expect("");
        uws_app_get(app, route.as_ptr(), ::std::option::Option::Some(get_handler));
        uws_app_listen(app, 3000, ::std::option::Option::Some(listen_handler));
        uws_app_run(app);
    }
}